### ISSUE TITLE
Restructure repo for more standardized implementations

### ISSUE THREAD

**Issue by NicholasACTran** [yashasvi-goel/Algorithms-Open-Source#16]
Instead of the repo being organized like:

- Language
    - Algorithm
        - Implementation

I propose that it is organized like:

- Algorithm
    - Language
        - Implementation

Thus, each Algorithm can have it's own ReadMe that'll go over the importance of the algorithm and a test case folder can be created to standardized the implementations across the languages.

**Comment by yashasvi-goel** [comment]
That's a good suggestion.

When I created this structure, I had the beginners in mind, ie. they can contribute according to the language they know because algorithms are being explored by them for the first time.

But the new way is clearly advantageous in terms of the algo-specific README.

Go ahead, reorganize it if you want and make a PR.

**Comment by michalirak** [comment]
Graph Algorithms/Cycle Detection/C++ is not restructured according to the new structure yet.

**Comment by yashasvi-goel** [comment]
@debargham14 Please do the needed for your code.
@NicholasACTran Please do the needed for your code.

**Comment by NicholasACTran** [comment]
Editing proposal:
- Algorithm Category
    - Algorithm Type
        - Language
            - Implementation

The idea being to keep certain algorithms that are similar, but distinct, close to each other (Graph Search and Cycle Detection)

**Comment by NicholasACTran** [comment]
Fixed in PR #36
